destination: _site/
url: "http://127.0.0.1:4016"
baseurl: "/alana-pdf"
port: 4016
output: pdf
product: alana
print_title: Alana Documentation
print_subtitle: version 1.0.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true