destination: _site/
url: "http://127.0.0.1:4016"
baseurl: "/avex-pdf"
port: 4016
output: pdf
product: avex
print_title: Avex Documentation
print_subtitle: version 1.0.x
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true